### ISSUE TITLE
Do I need to enable Databinding for this library to work??

### ISSUE THREAD

**Issue by ubarua123** [MaxKeppeler/bottom-sheets#6]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.getDefaultComponent(DataBindingUtil.java:65)
        at com.maxkeppeler.bottomsheets.databinding.BottomSheetsViewButtonsBinding.bind(BottomSheetsViewButtonsBinding.java:81)
        at com.maxkeppeler.bottomsheets.databinding.BottomSheetsBaseBinding.bind(BottomSheetsBaseBinding.java:71)
        at com.maxkeppeler.bottomsheets.databinding.BottomSheetsBaseBinding.inflate(BottomSheetsBaseBinding.java:57)
        at com.maxkeppeler.bottomsheets.core.BottomSheet.onCreateView(BottomSheet.kt:255)
```

**Comment by MaxKeppeler** [comment]
The library uses data and view binding. Your app doesn't need to use that. 
I guess, you missed adding the dependency to the ```core``` module, right?

```implementation 'com.maxkeppeler.bottomsheets:core:<latest-version>'```

It's required for every other module, as it is the base for them.

**Comment by MaxKeppeler** [comment]
I tried it out and removed the core module but included the info module on a fresh project. But even after adding the core module back, the warning persists. 

The library has the feature dataBinding included, but doesn't make use of it anymore. 
I will remove it therefore. 

If the library only uses viewBinding, in theory the warning shouldn't appear anymore - since it doesn't contain dataBinding anymore. 

Sorry for the issue!
